### ISSUE TITLE
set a timeout for connection to hashicorp vault ?

### ISSUE THREAD

**Issue by teto** [PierreBeucher/novops#101]
for the first time ever, I had novops 5646627ae73d1c6389dc99af9465dd4dae5afb2c stuck at
```
[2024-03-26T16:07:10Z DEBUG hyper::client::connect::dns] resolving host="mySecretGarden.com"
[2024-03-26T16:07:11Z DEBUG hyper::client::connect::http] connecting to resolvedSecretIP:443
```
the timeout looks long,  like >10mn if any ? if there is no timeout, should we add one ? otherwise perform some feedback that a request is pending.

**Comment by PierreBeucher** [comment]
Seems a good idea as a global config, will do

**Comment by PierreBeucher** [comment]
Solved with https://github.com/PierreBeucher/novops/pull/117

**Comment by PierreBeucher** [comment]
Ready in [0.15.0](https://github.com/PierreBeucher/novops/releases/tag/v0.15.0) :wink:
