### ISSUE TITLE
change the STS DurationSeconds value

### ISSUE THREAD

**Issue by teto** [PierreBeucher/novops#122]
Hi,

I am working on a project that need prolonged sessions of testing. Right now I have to reload my novops shell to renew the AWS credentials every hour. I was a bit surprised since I had changed the value in the IAM role to 4 hours. After checks, turns out I had just changed the Maximum duration to 4hours and the default remained to 1h. 
According to https://repost.aws/knowledge-center/iam-role-chaining-limit yu can change the session duration in awscli by passing DurationSeconds as option. I could not find how to enable this in novops https://novops.dev/config/aws.html#sts-assume-role ? Would it be possible to add ?

NB: I've just discovered that novops supported s3 buckets !! I've wanted to propose this, it opens up many possibilities. Congrats \o/

**Comment by PierreBeucher** [comment]
Definitely possible, actually was waiting for your issue apparently ;) https://github.com/PierreBeucher/novops/blob/main/src/modules/aws/client.rs#L85

> NB: I've just discovered that novops supported s3 buckets !! I've wanted to propose this, it opens up many possibilities. Congrats \o/

Hehe thanks ! I remember you proposed something like this a while back, someone else also did recently so I just went for it.

**Comment by PierreBeucher** [comment]
Coming next release with https://github.com/PierreBeucher/novops/pull/123

**Comment by PierreBeucher** [comment]
Released with https://github.com/PierreBeucher/novops/releases/tag/v0.16.0 :) Let me know so we can close this

**Comment by teto** [comment]
awesome. Haven't tested yet. Will reopen if I can't make it work :)
