### ISSUE TITLE
Mention similar tools in README

### ISSUE THREAD

**Issue by teto** [PierreBeucher/novops#41]
... for instance sops and https://github.com/channable/vaultenv/ .

I like projects that do that, it helps understand better what's the software + judge the competition.

**Comment by PierreBeucher** [comment]
A few I also use for inspiration:

- https://github.com/dotenv-org/dotenv-vault
- https://github.com/tellerops/teller
- https://github.com/sorah/envchain
- [https://github.com/Infisical/infisical export](https://infisical.com/docs/cli/commands/export)
- https://github.com/99designs/aws-vault

**Comment by teto** [comment]
wow teller looks impressive. Have you tried it yet ? looks close to novops, doesn't it ?

**Comment by PierreBeucher** [comment]
Indeed I had the same impression. However it does not manage files, can't generate temporary credentials like AWS creds and does not manage multi-environment (only a `context` can be given)

**Comment by PierreBeucher** [comment]
Solved in https://github.com/PierreBeucher/novops/pull/48
