### ISSUE TITLE
add `novops list` that list available environments

### ISSUE THREAD

**Issue by teto** [PierreBeucher/novops#61]
so that thay cab be piped into fzf such that `novops list | fzf | novops load -e {fzf_result}`

**Comment by PierreBeucher** [comment]
Solved by https://github.com/PierreBeucher/novops/pull/79

You'll be able to use `novops list environments` and `novops list environments` ;) Or in JSON like `novops list environments -o json`

**Comment by teto** [comment]
`novops list` has no description (in 0.15) which is sad :'(
```
sh-5.2# novops --help
Cross-plaform secret loader

Usage: novops [COMMAND]

Commands:
  load        Load a Novops environment. Output resulting environment variables to stdout or to a file using -s/--symlink. 
  run         Run a command with loaded environment variables and files.
  list        
  completion  Output completion code for various shells.
  schema      Output Novops config JSON schema
  help        Print this message or the help of the given subcommand(s)

Options:
  -h, --help     Print help
  -V, --version  Print version
  ```

**Comment by PierreBeucher** [comment]
Ah indeed, there are description for sub-commands `list outputs` and `list environments` though not the main one. Easy fix will come, thanks for the heads-up
