### ISSUE TITLE
in older novops, we could access the selected environment via NOVOPS_ENV

### ISSUE THREAD

**Issue by teto** [PierreBeucher/novops#67]
I dont think this is available anymore, which means most of the time you need to add an "ENVIRONMENT" command in your yaml file.
It could also be used to select a default environment for instance when running `novops run` (so you dont have to pass `-e dev` for instance)

**Comment by PierreBeucher** [comment]
This should be easy enough to add, will do ;) thanks for suggesting

**Comment by PierreBeucher** [comment]
On it: https://github.com/PierreBeucher/novops/pull/69

**Comment by PierreBeucher** [comment]
Will be released as part of https://github.com/PierreBeucher/novops/pull/66
