### ISSUE TITLE
Distributions for MacOS and Windows

### ISSUE THREAD

**Issue by tmeijn** [PierreBeucher/novops#90]
Hi! From the docs this tool looks really neat! We are considering either to adopt this one or Teller, but one downside of this tool is the lack of binaries for both MacOS and Windows. Is there any plan to support this and if so, any guesstimate on when?

**Comment by PierreBeucher** [comment]
Hi, thanks for your interested in Novops ! Mac support and multi-arch build is on my ASAP task, so expect something in the following weeks :) However I don't plan on Windows-native support just yet as [WSL](https://learn.microsoft.com/en-us/windows/wsl/install) should work fine - I'll test it and add doc if needed.

**Comment by crocuda** [comment]
Concerning MacOS, I have dived into Homebrew to make a first test for a Homebrew tape repo (the equivalent of a flake for NixOs) for pipelight. It is untested and unfinished but could give an hint on how to proceed to bring novops to the MacOs package manager https://github.com/pipelight/homebrew-pipelight

**Comment by PierreBeucher** [comment]
Mac support done with https://github.com/PierreBeucher/novops/pull/94 - I have yet to add full instructions to install on Mac, coming soon, but you have access to Mac-compatible binaries via release https://github.com/PierreBeucher/novops/releases/tag/v0.12.0

**Comment by PierreBeucher** [comment]
[Novops installation](https://novops.dev/install.html) now support Mac (natively) and Windows (via WSL). I don't intend for native Windows support for now, but it's possible if there's enough demand, feel free to comment here to re-open or open a new issue for Windows.
